---

- include: "playbooks/deploy_cluster.yml"
  tags: deploy_cluster
- name: Install group sync
  hosts: masters
  tasks:
    - name: Check Project
      shell: "oc get projects | grep {{ item.name }}"
      register: projectgrep
      with_items: "{{ projects }}"
      run_once: yes
      tags: ldap
    - debug: var=projectgrep
      tags: ldap
    - name: Create Project
      command: oc adm new-project {{ item.item.name }} --display-name="{{ item.item.text }}"
      when: 'item.rc == 1'
      with_items: "{{ projectgrep.results }}"
      run_once: yes
      tags: ldap
    - copy:
        src: files/ldap-group-sync.yml
        dest: /etc/origin/master/ldap-group-sync.yml
      tags: ldap
    - copy:
        src: files/whitelist.yml
        dest: /etc/origin/master/whitelist.yml
      tags: ldap
    - name: sync ldap once
      command: >-
        oc adm groups sync --sync-config=/etc/origin/master/ldap-group-sync.yml --whitelist=/etc/origin/master/whitelist.yml --confirm
      run_once: yes
      tags: ldap
    - name: add role to ldap group
      command: >-
        oc adm policy add-role-to-group {{ item.value.role }} {{ item.value.ldap_group }} -n {{ item.value.namespace }}
      with_dict: "{{ ldap_to_openshift_roles }}"
      run_once: yes
      tags: ldap
    - name: add cluster admin role
      command: >-
        oc adm policy add-cluster-role-to-group cluster-admin ocp-platform
      run_once: yes
      tags: ldap
    - name: add cluster admin role
      command: >-
        oc adm policy remove-cluster-role-from-group self-provisioner system:authenticated:oath
      run_once: yes
      tags: ldap
    - name: add cluster admin role
      command: >-
        oc adm policy add-scc-to-group anyuid system:serviceaccounts:paymentapp-prod
      run_once: yes
      tags: ldap
